services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL}
        REACT_APP_API_URL_MICROSERVICE2: ${REACT_APP_API_URL_MICROSERVICE2}
        REACT_APP_API_URL_MICROSERVICE3: ${REACT_APP_API_URL_MICROSERVICE3}
        REACT_APP_API_URL_MICROSERVICE4: ${REACT_APP_API_URL_MICROSERVICE4}
        REACT_APP_SIGNALR_URL: ${REACT_APP_SIGNALR_URL}
    ports:
      - "${PORT:-3000}:${NGINX_PORT:-80}"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
      - REACT_APP_API_URL_MICROSERVICE2=${REACT_APP_API_URL_MICROSERVICE2}
      - REACT_APP_API_URL_MICROSERVICE3=${REACT_APP_API_URL_MICROSERVICE3}
      - REACT_APP_API_URL_MICROSERVICE4=${REACT_APP_API_URL_MICROSERVICE4}
      - REACT_APP_SIGNALR_URL=${REACT_APP_SIGNALR_URL}
      - GENERATE_SOURCEMAP=${GENERATE_SOURCEMAP:-false}
    env_file:
      - .env.prod 